openapi: 3.0.0
info:
  title: API de Gestión de Citas Médicas - DLYTime
  description: API REST para la gestión de usuarios, autenticación, citas, historial clínico, empleados y clientes.
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Servidor local de desarrollo

tags:
  - name: Autenticacion
    description: Endpoints relacionados con autenticación y login.
  - name: CrudCita
    description: Endpoints para el manejo completo de citas médicas.
  - name: CrudCliente
    description: Endpoints para la gestión de clientes y su historial clínico.
  - name: CrudEmpleado
    description: Endpoints para la gestión de empleados.
  - name: Perfil
    description: Endpoints para visualizar y actualizar el perfil de usuario.
  - name: RecuperarPassword
    description: Endpoints para recuperación de contraseña y validación de código.

paths:
  /autenticacion/registro:
    post:
      tags:
        - Autenticacion
      summary: Registro de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroDocumento:
                  type: string
                idRol:
                  type: integer
                idTipoIdentificacion:
                  type: integer
                nombre:
                  type: string
                apellido:
                  type: string
                idGenero:
                  type: integer
                correo:
                  type: string
                clave:
                  type: string
      responses:
        '201':
          description: Usuario registrado con éxito
        '500':
          description: Error interno del servidor

  /autenticacion/login:
    post:
      tags:
        - Autenticacion
      summary: Inicio de sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo_i:
                  type: string
                password_i:
                  type: string
      responses:
        '200':
          description: Inicio de sesión exitoso
        '401':
          description: Credenciales inválidas o cuenta bloqueada
        '404':
          description: Usuario no encontrado

  /crudCitas/crudCita:
    get:
      tags:
        - CrudCita
      summary: Obtener citas filtradas
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: fecha
          schema:
            type: string
        - in: query
          name: idTipoConsulta
          schema:
            type: string
      responses:
        '200':
          description: Lista de citas obtenida exitosamente

  /crudCitas/addCita:
    post:
      tags:
        - CrudCita
      summary: Agregar una nueva cita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                NumeroDocumentoCliente:
                  type: string
                NumeroDocumentoOftalmologo:
                  type: string
                idHorario:
                  type: integer
                idTipoConsulta:
                  type: integer
      responses:
        '201':
          description: Cita agregada exitosamente
        '500':
          description: Error durante la transacción

  /crudCitas/updateCita:
    patch:
      tags:
        - CrudCita
      summary: Actualizar una cita existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - idCita
                - idHorario
                - idTipoConsulta
                - idHorario1
              properties:
                idCita:
                  type: integer
                idHorario:
                  type: integer
                idTipoConsulta:
                  type: integer
                idHorario1:
                  type: integer
      responses:
        '201':
          description: Cita actualizada exitosamente
        '500':
          description: Error durante la transacción

  /crudCitas/cancelCita:
    patch:
      tags:
        - CrudCita
      summary: Cancelar una cita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - idCita
                - idEstadoCita
                - idHorario
                - idEstadoHorario
              properties:
                idCita:
                  type: integer
                idEstadoCita:
                  type: integer
                idHorario:
                  type: integer
                idEstadoHorario:
                  type: integer
      responses:
        '201':
          description: Cita cancelada
        '400':
          description: No se puede activar una cita ya atendida
        '500':
          description: Error durante la transacción

  /crudClientes/consultaCliente:
    get:
      tags:
        - CrudCliente
      summary: Obtener lista de clientes
      responses:
        '200':
          description: Lista de clientes obtenida con éxito
        '500':
          description: Error al obtener los clientes

  /crudClientes/agregarCliente:
    post:
      tags:
        - CrudCliente
      summary: Agregar un nuevo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroDocumento:
                  type: string
                idTipoIdentificacion:
                  type: integer
                Nombres:
                  type: string
                Apellidos:
                  type: string
                correo:
                  type: string
                telefono:
                  type: string
                idGenero:
                  type: integer
                estadoPersona:
                  type: integer
      responses:
        '200':
          description: Cliente agregado con éxito
        '400':
          description: Faltan campos obligatorios
        '500':
          description: Error al agregar el cliente

  /crudClientes/actualizarCliente:
    patch:
      tags:
        - CrudCliente
      summary: Actualizar toda la información de un cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroDocumento:
                  type: string
                idTipoIdentificacion:
                  type: integer
                Nombres:
                  type: string
                Apellidos:
                  type: string
                correo:
                  type: string
                telefono:
                  type: string
                idGenero:
                  type: integer
                estadoPersona:
                  type: integer
      responses:
        '200':
          description: Cliente actualizado con éxito
        '400':
          description: Faltan campos obligatorios
        '404':
          description: Cliente no encontrado
        '500':
          description: Error al actualizar el cliente

  /crudEmpleados/consultaEmpleado:
    get:
      tags:
        - CrudEmpleado
      summary: Consultar empleados por número de documento
      parameters:
        - in: query
          name: q
          schema:
            type: string
      responses:
        '200':
          description: Lista de empleados

  /crudEmpleados/agregarEmpleado:
    post:
      tags:
        - CrudEmpleado
      summary: Agregar nuevo empleado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroDocumento:
                  type: string
                  example: "9999"
                idRol:
                  type: integer
                  example: 2
                idTipoIdentificacion:
                  type: integer
                  example: 2
                Nombres:
                  type: string
                  example: "Test"
                Apellidos:
                  type: string
                  example: "TestA"
                idGenero:
                  type: integer
                  example: 1
                correo:
                  type: string
                  example: "Test@gmail.com"
                telefono:
                  type: string
                  example: ""
                clave:
                  type: string
                  example: "Test123"
                idEstadoPersona:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Empleado registrado con éxito
        '400':
          description: Faltan campos obligatorios
        '500':
          description: Error al agregar el empleado

  /crudEmpleados/actualizarEmpleado:
    patch:
      tags:
        - CrudEmpleado
      summary: Actualizar datos del empleado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroDocumento:
                  type: string
                idTipoIdentificacion:
                  type: integer
                Nombres:
                  type: string
                Apellidos:
                  type: string
                idGenero:
                  type: integer
                correo:
                  type: string
                telefono:
                  type: string
                idEstadoPersona:
                  type: integer
      responses:
        '200':
          description: Empleado actualizado con éxito

  /perfil/datosUsuario:
    get:
      tags:
        - Perfil
      summary: Obtener datos del usuario por número de documento
      parameters:
        - in: query
          name: id
          schema:
            type: string
      responses:
        '200':
          description: Datos del usuario

  /perfil/updateUsuario:
    patch:
      tags:
        - Perfil
      summary: Actualizar datos del perfil del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroDocumento:
                  type: string
                nombre:
                  type: string
                apellido:
                  type: string
                telefono:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Datos actualizados

  /perfil/updateUsuarioAdmin:
    patch:
      tags:
        - Perfil
      summary: Actualizar contraseña por parte del administrador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroDocumento:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Datos actualizados
        '400':
          description: Error al actualizar los datos

  /recuperarPassword/validarCodigo:
    post:
      tags:
        - RecuperarPassword
      summary: Valida el código de recuperación de contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                code:
                  type: string
      responses:
        '200':
          description: Código válido
        '400':
          description: Código inválido o expirado
        '500':
          description: Error al validar el código

  /recuperarPassword/cambiarPassword:
    patch:
      tags:
        - RecuperarPassword
      summary: Cambia la contraseña del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                password:
                  type: string
                codigo:
                  type: string
      responses:
        '200':
          description: Contraseña cambiada con éxito
        '500':
          description: Error interno del servidor
